### ISSUE TITLE
currently cant override most templates as they are inside providers - eg subnet.erb and subnet-pool.erb

### ISSUE THREAD

**Issue by ITJamie** [sous-chefs/dhcp#117]
## :person_frowning: Problem Statement

Currently it does not appear to be feasible to overwrite the subnet.erb and subnet-pool.erb (called from within subnet.erb) that are called from the provider subnet.rb.

I need to be able to write some custom lines into each subnet-pool.erb entry to define monitoring variables that another tool will read from the subnet files.

## :grey_question: Possible Solution

additional variable options on the pool config that is added to the file. 
though having the ability to overwrite the erb files in the providers would also be excellent

## :heavy_plus_sign: Additional context

monitoring tool example conf http://folk.uio.no/trondham/software/dhcpd-pool.html for an example of one of these tools

**Comment by damacus** [comment]
I think we can do what you want with our usual extra options hash, which is just super flexible, and you should be able to pass a hash of values to it and allow you to do pretty much anything.

**Comment by bmhughes** [comment]
Implemented via #133
