### ISSUE TITLE
isc-dhcp-relay

### ISSUE THREAD

**Issue by floored1585** [sous-chefs/dhcp#63]
Would you be interested in having isc-dhcp-relay support in this cookbook?  I need this functionality and would be willing to submit a PR if it's something you'd like to include here.

**Comment by josephholsten** [comment]
I'd certainly be interested in seeing it!

**Comment by jmccann** [comment]
Yea, I'd be interested too.  I'm using relays right now myself so would be cool to control that with this potentially. :smile:

**Comment by floored1585** [comment]
Hum, so I went to work on this today and I can't figure out how to get the tests to run...  rubocop and foodcritic works fine but for anything else ruby 2.2.3 either crashes or runs into other issues.  Is there a recommended ruby to use for testing this cookbook?

**Comment by jmccann** [comment]
Testing with this cookbook is currently done with [ChefDK](https://downloads.chef.io/chef-dk/) 0.9.0 which has embedded ruby with version of 2.1.6p336

ChefDK 0.10.0 (latest) should also most likely work.

**Comment by floored1585** [comment]
Yikes, I finally got it working but had to uninstall rvm and the system ruby first.  Thanks for the help.

**Comment by damacus** [comment]
As part of pruning issues, I'm going to close this down now as it's been 2+ years since opening. 

If you'd like to continue this at a later date please feel free to reopen it! 

Thanks very much,
Dan
