### ISSUE TITLE
Invalid config shouldn't stop dhcpd service

### ISSUE THREAD

**Issue by Annih** [sous-chefs/dhcp#73]
Hello,

It could be very cool that an invalid config change does not stop the service.
A simple notification-chain performing a config check before restarting the service should be enough I think:

``` ruby
template 'config_file' 
service 'dhcpd'

execute 'check_dhcp_conf' do
  action :nothing
  command "dhcp -t -cf #{config_file} -lf #{leases}"
  subscribes :run, 'template[config_file]', :delayed
  notifies :restart, 'service[dhcpd]'
end  
```

I don't have time to provide a complete PR right now, that's why I just create an issue.

Regards.

**Comment by jmauro** [comment]
Any love for this Issue?

**Comment by shortdudey123** [comment]
@Annih do you have time now to submit a PR?
Otherwise, i can see what i can do when i have a bit more free time
