### ISSUE TITLE
Update to support ubuntu 16 and systemd instead of upstart

### ISSUE THREAD

**Issue by wesleung** [sous-chefs/dhcp#75]
In dhcp/recipes/_service.rb 
Figure remove the ubuntu 9 detection and just support Upstart and Systemd

```
service node['dhcp']['service_name'] do
  supports restart: true, status: true, reload: true
  action [:enable]
  case node['platform']
  when 'ubuntu'
    if node['platform_version'].to_f >= 16.04
      provider Chef::Provider::Service::Systemd
    else
      provider Chef::Provider::Service::Upstart
    end
  end
end
```

**Comment by shortdudey123** [comment]
I think the case statement can be removed in general since chef should be able to decide instead

**Comment by jmccann** [comment]
Is this to address a bug or just thinking about starting to remove support for old OS (code cleanup)?

**Comment by wesleung** [comment]
Current code fails as it forces Upstart when Ubuntu 16 is Systemd. Just looking to support both Ubuntu 14 and 16 with the same codebase

**Comment by jmccann** [comment]
ok, thnx ... will look into it!
