### ISSUE TITLE
auto-partner-down invalid statement in peer declaration

### ISSUE THREAD

**Issue by bcg62** [sous-chefs/dhcp#87]
Hitting this when trying to set up failover.

centos 6.9, dhcp-4.1.1-53.P1

```
dhcpd: /etc/dhcp/dhcpd.conf line 35: invalid statement in peer declaration
dhcpd:   auto-partner-down
dhcpd:    ^
dhcpd: Configuration file errors encountered -- exiting

**Comment by damacus** [comment]
Hey @bcg62 what platform is that happening on?

**Comment by bcg62** [comment]
@damacus centos 6.9
 dhcp-4.1.1-53.P1

**Comment by damacus** [comment]
That's not coming up in the kitchen tests (for 6.8 anyway) I'll update the tests and see if I can replicate. 

Any chance you can drop a config to replicate it in here please? Or open a PR with a kitchen test suite?

**Comment by bcg62** [comment]
@damacus I don't see any existing tests that use attributes to setup a failover/master/peer configuration unless im missing something.

I'm trying to recreate it but cant seem to force it into a master or peer mode with only attributes.

**Comment by bcg62** [comment]
I've tried adding this to the policy file, running chef update, and then running though test kitchen.

Its close but I cant seem to set the peer ip address.

```
default['dhcp']['failover'] = true
default['dhcp']['master'] = true
default['dhcp']['slaves'] = ['default-centos-68']
default['dhcp']['masters'] = ['default-centos-68']

**Comment by bcg62** [comment]
Were you able to reproduce it?  I could submit a PR to remove the option for centos 6 but I haven't been able to find much detail around it, if this is the correct course of action.

**Comment by bcg62** [comment]
still holding a fork to remove this option, would you entertain removing it?

**Comment by damacus** [comment]
Yep. If this unblock you, I'm all for that.

I'd entertain switching to the policyfile provisioner if that makes like easier for to replicate.

**Comment by damacus** [comment]
hey @bcg62 is there anything I need to do to resolve this for you? : )
