### ISSUE TITLE
RPM based systems fail (apt-get not guarded)

### ISSUE THREAD

**Issue by omgroves** [sous-chefs/dhcp#91]
### Cookbook version
5.4.1

### Chef-client version
12.9.41

### Platform Details
CentOS 7.3.1611

### Scenario:
Use this cookbook to install and manage dhcp

### Steps to Reproduce:
chef-client -o 'recipe[dhcp::server]'

### Expected Result:
dhcp::_package should install dhcp package

### Actual Result:
Chef fails because apt-get command does not exist on RPM based systems.
There is no guard to ensure `apt_update 'update'` is only run on Deb based systems. (_package.rb Line 1)

**Comment by damacus** [comment]
Chef Client 12.7 fixes this behaviour. 

We should update the required chef-client version 👍
